#!/bin/bash
echo "Starting local development server..."
echo "Note: Some features may not work locally without proper Cloudflare environment"
echo ""
echo "Available options:"
echo "1. Connect GitHub to Cloudflare Pages (recommended)"
echo "2. Use 'npx wrangler pages dev' for local testing"
echo ""
echo "Your Sheet Metal RAG system is configured with:"
echo "- D1 Database: e53b04c0-b1bc-495c-b7ca-8fea2de855b7"
echo "- Vectorize Index: cloudflare-rag-index"
echo "- KV Namespace: ac7c8ce52ab8402cbd1e2160ea0f7495"
echo "- R2 Bucket: cloudflare-rag-bucket"
echo ""
echo "Visit: https://sheet-metal-rag.pages.dev once connected to GitHub"