#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-rag"
compatibility_date = "2024-08-21"
pages_build_output_dir = "./build/client"

[placement]
mode = "smart"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "cloudflare-rag-index"

[[d1_databases]]
binding = "DB"                                       
database_name = "cloudflare-rag"
database_id = "e53b04c0-b1bc-495c-b7ca-8fea2de855b7" # your sheet metal shop database
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cloudflare-rag-bucket"

[[kv_namespaces]]
binding = "rate_limiter"
id = "ac7c8ce52ab8402cbd1e2160ea0f7495" # your rate limiter KV namespace
